@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package artifactsreloaded.api.main.util;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;